num_gpus: 2
train:
  enable: True
  checkpoint_metric: val/ED_step19_mean_naive
  checkpoint_mode: min
  batch_size: 32
val:
  batch_size: 32
test:
  enable: False
solver:
  num_epochs: 30
  warmup_epochs: 5
  lr: 2e-4
  optimizer: adam
  weight_decay: 1e-3
data:
  train_anno_path: data/ego4d/annotations/fho_lta_train.json
  val_anno_path: data/ego4d/annotations/fho_lta_val.json
  test_anno_path: data/ego4d/annotations/fho_lta_test_unannotated.json
  output_segments: [0, 20]
  input_segments: [-8, 0]
  input_from_annotated_segments: True
  image:
    fps: 30.0
    base_path: /gpfs/data/csun45/cfu17/GLIP_temp/output_CLIP_img_embedding_kmeans_ego4d
    num_images_per_segment: 4
    input_segments: [-8, 0]
  use_goal: True
  train_text_feature_path: text_features/ego4d_feature_train.pkl
  val_text_feature_path: text_features/ego4d_feature_recog_val.pkl
model:
  base_feat_size: 2048
  img_feat_size: 768
  text_feat_size: 768
  pte:
    num_layers: 3
    num_heads: 8
    enc_dropout: 0.1
    pos_dropout: 0.5
  drop_img: 0.3
  drop_text: 0.3
  num_actions_to_predict: 1
  total_actions_to_predict: 20
  loss_wts_heads: [1., 1.]
  loss_wts_temporal: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]