num_gpus: 4
train:
  enable: True
  checkpoint_metric: val/ED_step19_mean_naive
  checkpoint_mode: min
  batch_size: 32
val:
  batch_size: 32
test:
  enable: False
solver:
  num_epochs: 40
  warmup_epochs: 4
  lr: 1e-3
  weight_decay: 1e-3
  warmup_epochs: 3
data:
  train_anno_path: data/ego4d/annotations/fho_lta_train.json
  val_anno_path: data/ego4d/annotations/fho_lta_val.json
  test_anno_path: data/ego4d/annotations/fho_lta_test_unannotated.json
  output_segments: [0, 20]
  input_segments: [-8, 0]
  input_from_annotated_segments: True
  image:
    fps: 30.0
    base_path: data/output_CLIP_img_embedding_ego4d
    num_images_per_segment: 4
    input_segments: [-8, 0]
model:
  use_vid: False
  base_feat_size: 2048
  img_feat_size: 768
  pte:
    num_layers: 3
    num_heads: 8
    enc_dropout: 0.1
    pos_dropout: 0.5
  drop_img: 0.3
  num_actions_to_predict: 20
  loss_wts_heads: [1., 1.]
  loss_wts_temporal: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]